### PR TITLE
Attest trezor-firmare core/v2.6.0 with mac support

### PR DESCRIPTION
**Pull request by fletcher86**
Verified build using macOS Ventura 13.3.1 (a) (22E772610a)

### CODE REVIEW

**Comment by brianddk** [comment]
Awesome.  I'll tag the current tree at v0.1 then merge and tag at v0.2

After the merge I'll cut a new branch "mac-support" to try some revisions.  I'll test for `shasum` and `grealpath` to prevent the need for extra installs or symlinks.  But at this point ChatGPT is may macOS consultant, so might need someone to check my work.

**Comment by fletcher86** [comment]
Sure np

**Comment by brianddk** [comment]
OK... see if the `mac_support` branch works.  I've put a bunch of the version checks into `settings.sh`.

https://github.com/brianddk/attestation/tree/mac_support

Also, your attest file had mis-matched checksums so I failed it, but hopefully you can get a clean build with the updates.

**Comment by fletcher86** [comment]
Ok, I'll see if I can get to it. (at the very latest this weekend).  Been really busy today on my day job.

**Comment by brianddk** [comment]
Sure... thx... BTW... grab latest, Just pushed 519f0c4 with a few more changes.

**Comment by fletcher86** [comment]
Here is a screenshot of the checksum.  I'm getting the same value I got before.  I wonder if its because I'm running an M1 chip for my macbook air?
image

**Comment by fletcher86** [comment]
qq:

Should the checksums be the same for each 'trezor-2.6.0.bin' and 'repo/build/core/firmware/firmware.bin' below?

c33e336869964cfb1ef193195894e8b6667955b4ea3044558c380b1787168e38  trezor-2.6.0.bin
d8650a84f119ac1cde2bf7f07471aa8f75cabad90e8e8a99707e9d8fcdf40028  repo/build/core/firmware/firmware.bin

c0b7696ce45ac9fe593eb9af1eb561f66cdf8be4d6a6bea6e538e252843e8a2f  trezor-2.6.0-bitcoinonly.bin
17619deda90e1bf9e3170b15b82c67acd2f1b5e3ebd969199372ed34e2dfbe9f  repo/build/core-bitcoinonly/firmware/firmware.bin

**Pull request merged**
